site_name: OpenbotV-v0
site_url: https://mydomain.org/mysite
theme:
  name: material

nav:
  - Home:
      - index.md
  - API Docs:
      - Data:
          - Control Utils: developer-guide/data/control_utils.md
          - Controller: developer-guide/data/controller.md
plugins:
  - search
  - mkdocstrings
