@startuml packages_MiProyecto
set namespaceSeparator none
package "src" as src {
}
package "src.data" as src.data {
}
package "src.data.control_utils" as src.data.control_utils {
}
package "src.data.controller" as src.data.controller {
}
package "src.gui" as src.gui {
}
package "src.gui.app_interface" as src.gui.app_interface {
}
package "src.gui.camera_interface" as src.gui.camera_interface {
}
package "src.gui.camera_worker" as src.gui.camera_worker {
}
package "src.gui.graph_interface" as src.gui.graph_interface {
}
package "src.gui.graph_worker" as src.gui.graph_worker {
}
package "src.gui.main_window" as src.gui.main_window {
}
package "src.gui.main_window.image_utils_mixin" as src.gui.main_window.image_utils_mixin {
}
package "src.gui.main_window.main_actions_mixin" as src.gui.main_window.main_actions_mixin {
}
package "src.gui.main_window.main_init_mixin" as src.gui.main_window.main_init_mixin {
}
package "src.gui.main_window.main_menu_mixin" as src.gui.main_window.main_menu_mixin {
}
package "src.gui.main_window.main_theme_mixin" as src.gui.main_window.main_theme_mixin {
}
package "src.gui.main_window.main_title_bar_mixin" as src.gui.main_window.main_title_bar_mixin {
}
package "src.gui.main_window.theme_stylesheet" as src.gui.main_window.theme_stylesheet {
}
package "src.gui.main_window.theme_stylesheet.dark" as src.gui.main_window.theme_stylesheet.dark {
}
package "src.gui.main_window.theme_stylesheet.light" as src.gui.main_window.theme_stylesheet.light {
}
package "src.gui.simulation_interface" as src.gui.simulation_interface {
}
package "src.gui.simulation_worker" as src.gui.simulation_worker {
}
package "src.gui.sliders_interface" as src.gui.sliders_interface {
}
package "src.main" as src.main {
}
package "src.robot" as src.robot {
}
package "src.robot.openbotv_worker" as src.robot.openbotv_worker {
}
package "src.simulation" as src.simulation {
}
package "src.simulation.physics_pybullet" as src.simulation.physics_pybullet {
}
package "src.simulation.physics_worker" as src.simulation.physics_worker {
}
package "src.vision" as src.vision {
}
package "src.vision.camera" as src.vision.camera {
}
package "src.vision.camera_chessboard" as src.vision.camera_chessboard {
}
package "src.vision.chessboard" as src.vision.chessboard {
}
src.main --> src.gui.app_interface
@enduml
